### ISSUE TITLE
Help newbies for find the MAC adress 

### ISSUE THREAD

**Issue by tanguyp14** [HoroTW/pixoo-awesome#2]
Hello i have th Pixoo Max too, i wanna use some custom image to it the app is lame. 

How i use yours ? I don' know how to have MAC adress of the PIxoo Max

**Comment by HoroTW** [comment]
Hey,
no problem I will walk you through it.
First of all what OS are you using? :)

**Comment by tanguyp14** [comment]
Thank for responding !
Im on MAC OS

**Comment by HoroTW** [comment]
So I'm not familiar with macOS,
after some googling, it seems that you would just need to pair the pixoo with your macOS device.
After pairing, you need to execute
```
system_profiler SPBluetoothDataType
```
Which will then include the mac address for the pixoo device.

Let me know if you need more assistance.

**Comment by tanguyp14** [comment]
Omg. I didn't know i can pair it with my Mac 🙀
Ok i got the MAC adr. 
I will follow the readme ! Thanks

**Comment by tanguyp14** [comment]
OK so now i got error : (yeah !) 

I pair it with my laptop and i got the MAC adress.
But : 
`❱❱❱ python pixoo.py
11:75:58:38:7A:31
Connecting to 11:75:58:38:7A:31...
Traceback (most recent call last):
  File "/Users/tanguypinel/Downloads/pixoo-awesome-main/pixoo.py", line 20, in <module>
    pixoo.connect()
  File "/Users/tanguypinel/Downloads/pixoo-awesome-main/modules/pixoo_client.py", line 39, in connect
    self.btsock = socket.socket(socket.AF_BLUETOOTH, socket.SOCK_STREAM, socket.BTPROTO_RFCOMM)
AttributeError: module 'socket' has no attribute 'AF_BLUETOOTH'
[13:20:39] [cost 0.160s] python pixoo.py   `

**Comment by HoroTW** [comment]
Which python version do you have? (find out with `python --version`)

**Comment by tanguyp14** [comment]
I use :
> Python3 --version 
> Python 3.10.9

**Comment by HoroTW** [comment]
Okay I found the culprit...
As described in this issue on StackOverflow: https://stackoverflow.com/questions/29107537/missing-socket-af-bluetooth-in-anaconda-python
MacOS is special in it's handling of Bluetooth .... The native python way that the pixooclient uses is sadly not compatible with macOS... (see https://docs.python.org/3.3/library/socket.html)
Do you have another device maybe a single board computer like a RPI? (That is the way I use this project)

**Comment by tanguyp14** [comment]
I think i have pc can run Linux ! 
But the PC need to be "online" all time to set up the pixoo ? Or just for sending information ?
(Thanks for your responses anyway !)

**Comment by HoroTW** [comment]
I will see if I can implement a version using `PyBluez` - they claim that they are cross platform compatible (including macOS - https://github.com/pybluez/pybluez)....

But I'm currently moving and a little short on time, I guess it will take a few months until I'll be able to tackle this.
If you want you can try it yourself, pull requests are welcome.

The PC would need to be turned on - the PC calculates the picture and sends it for display to the pixoo. I would have liked to do it differently but I did not find any way to execute code on the pixoo itself.

Currently I animate a clock and have some Pixels indicating statuses for things like if I did a 'daily commit'.
![20220109_011629](https://user-images.githubusercontent.com/8217773/209679184-fc07796c-d9f9-40d2-8125-1c3a46a87a8d.jpg)

**Comment by tanguyp14** [comment]
That a cool set-up !
I stream so i would like to interact with the pixoo but is kinda "hard" ^^' 
Nevermind i will try on linux, or even on rapsberry(like) just to display custom 'FAKING' clock ^^

Happy moving ! thanks again :D

**Comment by manisfive** [comment]
Have you thought about coming back to this? I don't mind giving it a try but I'll be kinda mashing puzzle pieces together to try and make them fit

**Comment by HoroTW** [comment]
Hey hey, this does still work, what would you like to try?

**Comment by manisfive** [comment]
Nice! I meant the MacOs compatibility specifically
I do recording on my mac and I'd love to mirror part of my screen to the pixoo to get a more elaborate visualizer going

**Comment by HoroTW** [comment]
I do not have a Mac machine, so testing this is kind of hard for me ^^, but I would assume that it should work well.

For the "mirror part of my screen" part, I would say the code should be straightforward.

Take a screenshot (or just a part of the screen) every 100ms and use pillow to resize it to the pixel count of your pixoo device and then send the image to it.

It is very similar to the clock, but instead of creating the clock image, you just take the new screenshot.

If you try this and get stuck, I can provide additional guidance. 😊

**Comment by manisfive** [comment]
Ah that is super helpful! I think I read this thread and just thought it wasn’t working on Mac. I’ll give it a try, thanks!
